#!/usr/bin/env python3
"""Ingest real coastal events into data/events-generated.json.

  fetch -> normalize -> validate -> deduplicate -> write

Editorial overrides live in data/events-editorial.json and are applied at
render time, so the generated file stays purely machine-produced and can be
regenerated at any moment without losing an editor's decisions.

Resilience: each source is fetched independently. If a source fails, its
previously ingested records are carried forward. If EVERY source fails, the
existing file is left untouched rather than emptied.

Usage:
  python3 scripts/ingest_events.py            # ingest and write
  python3 scripts/ingest_events.py --dry-run  # report only
"""
import json
import os
import sys
from datetime import datetime, timedelta, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
REPO = os.path.dirname(HERE)
OUT = os.path.join(REPO, 'data', 'events-generated.json')

from events.dedupe import dedupe                        # noqa: E402
from events.sources import bethany, historic_lewes, rehoboth   # noqa: E402

SOURCES = [rehoboth, historic_lewes, bethany]
# Keep a short tail of finished events so a page loaded near midnight does not
# lose its context; current-facing filtering happens at render time.
KEEP_PAST_DAYS = 2


def main():
    dry = '--dry-run' in sys.argv
    stamp = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
    today = datetime.now(timezone.utc).astimezone(
        timezone(timedelta(hours=-4))).date()
    floor = (today - timedelta(days=KEEP_PAST_DAYS)).isoformat()

    prev = {}
    if os.path.exists(OUT):
        try:
            prev = json.load(open(OUT, encoding='utf-8'))
        except (ValueError, OSError):
            prev = {}
    prev_events = prev.get('events') or []

    collected, reports = [], []
    for mod in SOURCES:
        events, rep = mod.fetch()
        reports.append(rep)
        print('  %-26s %-22s discovered %3d  accepted %3d  rejected %2d  %s'
              % (rep['source'], rep['method'], rep['discovered'],
                 rep['accepted'], rep['rejected'],
                 'ok' if rep['ok'] else 'FAILED: %s' % rep['error']))
        if rep['ok']:
            collected.extend(events)
        else:
            # Carry this source's previous records forward untouched.
            carried = [e for e in prev_events if e.get('sourceName') == rep['source']]
            for c in carried:
                c = dict(c)
                c['carriedForward'] = True
            collected.extend(carried)
            print('     carried forward %d previously ingested record(s)' % len(carried))

    ok_sources = [r for r in reports if r['ok']]
    if not ok_sources:
        print('\n  every source failed — leaving the existing file untouched.')
        return 1

    # Drop events that finished more than KEEP_PAST_DAYS ago.
    fresh = [e for e in collected if (e.get('endDate') or e['startDate']) >= floor]
    expired = len(collected) - len(fresh)

    kept, removed = dedupe(fresh)
    kept.sort(key=lambda e: (e['startDate'], e.get('startTime') or '', e['title']))

    out = {
        '_note': ('Machine-ingested factual event records. Do not hand-edit: this '
                  'file is regenerated by scripts/ingest_events.py. Editorial '
                  'decisions belong in data/events-editorial.json.'),
        'generatedAt': stamp,
        'timezone': 'America/New_York',
        'sources': reports,
        'counts': {'collected': len(collected), 'expired': expired,
                   'duplicatesRemoved': removed, 'published': len(kept)},
        'events': kept,
    }

    print('\n  collected %d  expired %d  duplicates removed %d  published %d'
          % (len(collected), expired, removed, len(kept)))

    if dry:
        print('\nDRY RUN — nothing written.')
        return 0
    with open(OUT, 'w', encoding='utf-8') as fh:
        json.dump(out, fh, indent=2, ensure_ascii=False)
        fh.write('\n')
    print('  wrote %s' % os.path.relpath(OUT, REPO))
    return 0


if __name__ == '__main__':
    sys.exit(main())
